### ISSUE TITLE
Error with binary sequence classification

### ISSUE THREAD

**Issue by ted537** [EricFillion/happy-transformer#135]
When running the `train_sequence_classifier()` function, even from a fresh venv install, this error occurs

```
>>> transformer.train_sequence_classifier("~/git/happy-transformer/tests/example_seq_train.csv")
06/06/2020 16:55:50 - INFO - happytransformer.happy_transformer -   ***** Running Training *****
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 233.02it/s]
Epoch:   0%|                                                                                                          | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ted/code/venv/lib/python3.8/site-packages/tqdm/notebook.py", line 96, in status_printer
    pbar = IProgress(min=0, max=total)
NameError: name 'IProgress' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ted/code/venv/lib/python3.8/site-packages/happytransformer/happy_transformer.py", line 382, in train_sequence_classifier
    self.seq.train_model()
  File "/home/ted/code/venv/lib/python3.8/site-packages/happytransformer/sequence_classifier.py", line 82, in train_model
    self.__train()
  File "/home/ted/code/venv/lib/python3.8/site-packages/happytransformer/sequence_classifier.py", line 123, in __train
    epoch_iterator = tqdm_notebook(train_dataloader, desc="Iteration")
  File "/home/ted/code/venv/lib/python3.8/site-packages/tqdm/__init__.py", line 28, in tqdm_notebook
    return _tqdm_notebook(*args, **kwargs)
  File "/home/ted/code/venv/lib/python3.8/site-packages/tqdm/notebook.py", line 208, in __init__
    self.container = self.status_printer(
  File "/home/ted/code/venv/lib/python3.8/site-packages/tqdm/notebook.py", line 103, in status_printer
    raise ImportError(
ImportError: FloatProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.htm
```

**Comment by EricFillion** [comment]
Thanks for pointing out this bug! I will look into it and get back to you
